services:
  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - "${PORT-7700}:7700"
    environment:
      MEILI_MASTER_KEY: "${API_KEY-masterKey}"
      MEILI_NO_ANALYTICS: "true"
